[package]
name = "sudoku-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "board"
harness = false

[[bench]]
name = "backtracking"
harness = false
